apiVersion: v1
kind: Service
metadata:
  name: hsqldb-svc
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9002

---

apiVersion: v1
kind: Endpoints
metadata:
  name: hsqldb-svc
subsets:
  - addresses:
      - ip: 172.17.241.129
    ports:
      - port: 9002