apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoappserver
  labels:
    app: todoappserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoappserver
  template:
    metadata:
      labels:
        app: todoappserver
    spec:
      containers:
        - name: todoappserver
          image: ayortanli/todoappserver:1.1.0
          env:
            - name: DB_URL
              value: jdbc:hsqldb:hsql://hsqldb-svc:9000/todoapp-db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todoappdbsecret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todoappdbsecret
                  key: password
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todoappserver-svc
  labels:
    app: todoappserver
spec:
  selector:
    app: todoappserver
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP